#
# Vagrantの設定
#
- hosts: all
  become: yes
  user: vagrant
  vars:
    db_name: hoge
    db_user: fuga
    db_password: hidebu
    laravel_home: /home/vagrant/laravel6
    app_name: hoge
    app_url: http://hoge.local
    ssh_home: /home/vagrant/.ssh
  roles:
    - common
    - php
    - nginx
    - mariadb
    - laravel
    - bitbucket
  tasks:
    - name: Gitのインストール
      yum:
        name: git
