#
# Vagrantの設定
#
- hosts: all
  become: yes
  user: vagrant
  vars:
    db_name: hoge
    db_user: fuga
    db_password: hidebu
  roles:
    - common
    - php
    - nginx
    - mariadb
    - laravel
  tasks:
    - name: Gitのインストール
      yum:
        name: git
