- hosts: all
  become: yes
  user: vagrant
  vars:
  tasks:
    # SELinux無効
    - name: SELinuxのDisable設定
      selinux: state=disabled

    # ファイアーウォール無効
    - name: ファイアーウォール無効
      systemd:
        name: firewalld
        state: stopped
        enabled: false

    # IPV6無効
    - name: IPV6無効
      replace: 
        dest=/etc/default/grub
        regexp='GRUB_CMDLINE_LINUX="crashkernel=auto spectre_v2=retpoline rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet biosdevname=0 net.ifnames=0"'
        replace='GRUB_CMDLINE_LINUX="ipv6.disable=1 crashkernel=auto spectre_v2=retpoline rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet biosdevname=0 net.ifnames=0"'

    # yum
    - name: yumリポジトリの登録
      yum: name={{ item }}
      with_items:
        - epel-release
        - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

    # Nginx
    - name: Nginxをインストール
      yum: name=nginx

    # PHP
    - name: PHPをインストール
      yum: name={{ item }} enablerepo=remi,remi-php73 state=installed
      with_items:
        - php
        - php-devel
        - php-mbstring
        - php-pdo
        - php-gd
        - php-xml
        - php-mcrypt
        - php-mysqlnd
        - php-fpm
        - php-pecl-xdebug
        - php-pecl-zip
        - php-bcmath

    - name: XDebug設定
      lineinfile:
        dest=/etc/php.ini
        line={{ item }}
      with_items:
        - 'xdebug.remote_enable = On'
        - 'xdebug.remote_autostart = On'
        - 'xdebug.remote_connect_back = 1'
        - 'xdebug.remote_port = 9000'
        - 'xdebug.scream = 0'
        - 'xdebug.show_local_vars = 1'
        - 'xdebug.idekey=PHPSTORM'

    - name: PHP-FPM設定
      lineinfile: 
        dest=/etc/php-fpm/www.conf
        regexp='{{ item.regexp }}'
        line='{{ item.line }}'
      with_items:
        - regexp: '^user = apache'
          line: 'user = nginx'
        - regexp: '^group = apache'
          line: 'group = nginx'
        - regexp: '^listen = 127.0.0.1:9000'
          line: 'listen = /var/run/php-fpm/php-fpm.sock'
        - regexp: '^;listen.owner = nobody'
          line: 'listen.owner = nginx'
        - regexp: '^;listen.group = nobody'
          line: 'listen.group = nginx'
        - regexp: '^;listen.mode = 0660'
          line: ';listen.mode = 0660'

#     - name: Nginx設定

    # MariaDB
    - name: MariaDBのリポジトリを追加
      command: >
        curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash
        curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash -s -- --mariadb-server-version=mariadb-10.3

    - name: MariaDBをインストール
      yum: name={{item}}
      with_items:
        - MariaDB-server
        - MariaDB-client

    - name: MariaDBを起動
      service: name=mariadb state=started enabled=yes

    - name: DB作成
      mysql_db: name=hoge state=present

    - name: ユーザー作成
      mysql_user: name=fuga password=hidebu priv=*.*:ALL state=present host={{item}}
      with_items:
        - '%'
        - 'localhost'

    # Gitのインストール
    - name: Gitのインストール
      yum: name=git