#
# Laravelハンドラ
#
- name: いろいろクリア
  become: no
  command: |
    cd "{{ laravel_home }}"
    php artisan view:clear
    php artisan cache:clear
    php artisan config:clear
    php artisan route:clear
    php artisan clear-compiled
    php artisan config:cache
    composer dump-autoload
    php artisan ide-helper:generate
    php artisan ide-helper:models -N
    php artisan ide-helper:meta
    find . -name '._.DS_Store' -type f -ls -delete
  listen: laravel handler

- name: マイグレーション
  become: no
  command: |
    cd "{{ laravel_home }}"
    php artisan migrate
    php artisan db:seed
  listen: laravel handler

- name: パーミッション変更
  become: no
  command: |
    cd "{{ laravel_home }}"
    chmod -R 777 storage
    chmod -R 777 bootstrap/cache
  listen: laravel handler

- name: 所有者を変更
  become: yes
  command: |
    cd "{{ laravel_home }}"
    chown nginx:nginx storage/logs
    chown nginx:nginx storage/framework/views
  listen: laravel handler
