#
# Laravelハンドラ
#
- name: composer update
  become: no
  command: composer update
  listen: laravel handler

- name: clear laravel
  become: no
  command: |
    php artisan view:clear
    php artisan cache:clear
    php artisan config:clear
    php artisan route:clear
    php artisan clear-compiled
    php artisan config:cache
    composer dump-autoload
    php artisan ide-helper:generate
    php artisan ide-helper:models -N
    php artisan ide-helper:meta
    find . -name '._.DS_Store' -type f -ls -delete
  listen: laravel handler
