#
# MariaDBのインストールおよび設定
#
- name: MariaDBのリポジトリを追加
  shell: curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash -s -- --mariadb-server-version=mariadb-10.3

- name: MariaDBをインストール
  yum:
    name: ['MariaDB-server', 'MariaDB-client']

- name: MariaDBを起動
  service:
    name: mariadb
    state: started
    enabled: yes

- name: 必須ライブラリをインストール
  yum:
    name: MySQL-python
    state: present
    enablerepo: epel

- name: DB作成
  mysql_db:
    name: ”{{ db_name }}”
    state: present

- name: ユーザー作成
  mysql_user:
    name: ”{{ db_user }}”
    password: ”{{ db_password }}”
    priv: '*.*:ALL'
    state: present
    host: "{{ item }}"
  with_items:
    - '%'
    - 'localhost'