#
# BitbucketのSSH接続設定
#
- name: ディレクトリ作成
  file:
    path: "{{ ssh_home }}"
    state: directory
    mode: 0700

- name: キー作成
  become: no
  openssh_keypair:
    path: "{{ ssh_home }}/id_rsa"

- name: 公開キー出力
  become: no
  shell: cat {{ ssh_home }}/id_rsa.pub
  register: result

- name: 公開キー出力結果
  debug:
    msg: ”{{ result.stdout }}”

- name: 設定ファイル作成
  become: no
  shell: |
    cd {{ ssh_home }}
    touch config
    chmod 700 config

- name: 接続設定
  become: no
  lineinfile:
    dest: ~/.ssh/config
    line: "{{ item }}"
  with_items:
    - 'Host bitbucket.org'
    - '  HostName bitbucket.org'
    - '  IdentityFile ~/.ssh/id_rsa'
    - '  User git'
    - '  Port 22'
    - '  TCPKeepAlive yes'
    - '  IdentitiesOnly yes'